import NavBar from "./nav";
import ToastApp from "../components/toast";
import "bootstrap/dist/css/bootstrap.min.css";

export const metadata = {
  title: "Shopify",
  description: "Generated by SHOPIFY",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/x-icon" href="/favicon.jpeg"></link>
      </head>
      <body>
        <NavBar></NavBar>


            <ToastApp children={children}>
            </ToastApp>

      </body>
    </html>
  );
}
